#!/usr/bin/env python2.7
#  -*- coding: utf-8 -*-
#

import subprocess, os, string, time, sys ,getopt, ConfigParser
server_list=[]


def add_server_list():
	###################add server list #########################
	config = ConfigParser.ConfigParser()
	config.read('/CTS_tool/for_pythonUI/WiFiconfig.ini')
	sum = 0   # 累加變數
	#i = 1   # 索引變數
	for i in config.items('Server IP'):
		server_name= str(config.items('Server IP')[sum]).split(",",)[0].split("(",)[1].replace("'", "")#GET "Value_ABC"
		server_IP = str(config.items('Server IP')[sum]).split(" '",)[1].split("'",)[0]#GET "Value_ABC"
		server_list.append(server_name+"@"+server_IP)
		sum=sum+1


def rsync():
	############rsync server #################
	for i in  server_list:
		output="sshpass -p '1' rsync -zarv --include='*.zip' --exclude '*' '/CTS_tool/old_script/' "+i+"':/CTS_tool/old_script/'"
		print str(output)	
		p=subprocess.Popen(output, shell=True)
		print str(i)

add_server_list()
rsync()
